import type { Metadata } from "next";
import "@/shared/styles/globals.css";
import AppProvider from "@/shared/providers/app-provider";
import { GeistSans } from "geist/font/sans";
import { ViewTransitions } from "next-view-transitions";

export const metadata: Metadata = {
  title: "Ignix App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="pt-br">
        <body className={`${GeistSans.className} bg-background`}>
          <AppProvider>{children}</AppProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
